id,album_id,artist_id,path,web_path,title,track_number,year,genre,duration
;1;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - Powerage/02 - AC-DC - Down Payment Blues.mp3;/music/AC-DC/1978 - Powerage/02 - AC-DC - Down Payment Blues.mp3;Down Payment Blues;02;1978;Hard Rock;6:04
;1;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - Powerage/01 - AC-DC - Rock 'N' Roll Damnation.mp3;/music/AC-DC/1978 - Powerage/01 - AC-DC - Rock 'N' Roll Damnation.mp3;Rock 'N' Roll Damnation;01;1978;Hard Rock;3:38
;1;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - Powerage/09 - AC-DC - Kicked In The Teeth.mp3;/music/AC-DC/1978 - Powerage/09 - AC-DC - Kicked In The Teeth.mp3;Kicked In The Teeth;09;1978;Hard Rock;4:03
;1;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - Powerage/06 - AC-DC - What's Next To The Moon.mp3;/music/AC-DC/1978 - Powerage/06 - AC-DC - What's Next To The Moon.mp3;What's Next To The Moon;06;1978;Hard Rock;3:32
;1;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - Powerage/07 - AC-DC - Gone Shootin'.mp3;/music/AC-DC/1978 - Powerage/07 - AC-DC - Gone Shootin'.mp3;Gone Shootin';07;1978;Hard Rock;5:06
;1;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - Powerage/03 - AC-DC - Gimme A Bullet.mp3;/music/AC-DC/1978 - Powerage/03 - AC-DC - Gimme A Bullet.mp3;Gimme A Bullet;03;1978;Hard Rock;3:22
;1;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - Powerage/05 - AC-DC - Sin City.mp3;/music/AC-DC/1978 - Powerage/05 - AC-DC - Sin City.mp3;Sin City;05;1978;Hard Rock;4:45
;1;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - Powerage/04 - AC-DC - Riff Raff.mp3;/music/AC-DC/1978 - Powerage/04 - AC-DC - Riff Raff.mp3;Riff Raff;04;1978;Hard Rock;5:12
;1;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - Powerage/08 - AC-DC - Up To My Neck In You.mp3;/music/AC-DC/1978 - Powerage/08 - AC-DC - Up To My Neck In You.mp3;Up To My Neck In You;08;1978;Hard Rock;4:13
;2;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/2000 - Stiff Upper Lip/11 - AC-DC - All Screwed Up.mp3;/music/AC-DC/2000 - Stiff Upper Lip/11 - AC-DC - All Screwed Up.mp3;All Screwed Up;11;2000;Hard Rock;4:37
;2;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/2000 - Stiff Upper Lip/09 - AC-DC - Damned.mp3;/music/AC-DC/2000 - Stiff Upper Lip/09 - AC-DC - Damned.mp3;Damned;09;2000;Hard Rock;3:52
;2;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/2000 - Stiff Upper Lip/07 - AC-DC - Can't Stop Rock 'N' Roll.mp3;/music/AC-DC/2000 - Stiff Upper Lip/07 - AC-DC - Can't Stop Rock 'N' Roll.mp3;Can't Stop Rock 'N' Roll;07;2000;Hard Rock;4:02
;2;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/2000 - Stiff Upper Lip/02 - AC-DC - Meltdown.mp3;/music/AC-DC/2000 - Stiff Upper Lip/02 - AC-DC - Meltdown.mp3;Meltdown;02;2000;Hard Rock;3:41
;2;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/2000 - Stiff Upper Lip/01 - AC-DC - Stiff Upper Lip.mp3;/music/AC-DC/2000 - Stiff Upper Lip/01 - AC-DC - Stiff Upper Lip.mp3;Stiff Upper Lip;01;2000;Hard Rock;3:35
;2;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/2000 - Stiff Upper Lip/03 - AC-DC - House Of Jazz.mp3;/music/AC-DC/2000 - Stiff Upper Lip/03 - AC-DC - House Of Jazz.mp3;House Of Jazz;03;2000;Hard Rock;3:56
;2;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/2000 - Stiff Upper Lip/04 - AC-DC - Hold Me Back.mp3;/music/AC-DC/2000 - Stiff Upper Lip/04 - AC-DC - Hold Me Back.mp3;Hold Me Back;04;2000;Hard Rock;3:59
;2;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/2000 - Stiff Upper Lip/10 - AC-DC - Come And Get It.mp3;/music/AC-DC/2000 - Stiff Upper Lip/10 - AC-DC - Come And Get It.mp3;Come And Get It;10;2000;Hard Rock;4:03
;2;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/2000 - Stiff Upper Lip/06 - AC-DC - Can't Stand Still.mp3;/music/AC-DC/2000 - Stiff Upper Lip/06 - AC-DC - Can't Stand Still.mp3;Can't Stand Still;06;2000;Hard Rock;3:42
;2;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/2000 - Stiff Upper Lip/05 - AC-DC - Safe In New York City.mp3;/music/AC-DC/2000 - Stiff Upper Lip/05 - AC-DC - Safe In New York City.mp3;Safe In New York City;05;2000;Hard Rock;3:59
;2;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/2000 - Stiff Upper Lip/12 - AC-DC - Give It Up.mp3;/music/AC-DC/2000 - Stiff Upper Lip/12 - AC-DC - Give It Up.mp3;Give It Up;12;2000;Hard Rock;4:13
;2;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/2000 - Stiff Upper Lip/08 - AC-DC - Satellite Blues.mp3;/music/AC-DC/2000 - Stiff Upper Lip/08 - AC-DC - Satellite Blues.mp3;Satellite Blues;08;2000;Hard Rock;3:47
;3;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - If You Want Blood, You've Got It/03 - AC-DC - Bad Boy Boogie.mp3;/music/AC-DC/1978 - If You Want Blood, You've Got It/03 - AC-DC - Bad Boy Boogie.mp3;Bad Boy Boogie;03;1978;Hard Rock;7:27
;3;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - If You Want Blood, You've Got It/04 - AC-DC - The Jack.mp3;/music/AC-DC/1978 - If You Want Blood, You've Got It/04 - AC-DC - The Jack.mp3;The Jack;04;1978;Hard Rock;5:50
;3;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - If You Want Blood, You've Got It/06 - AC-DC - Whole Lotta Rosie.mp3;/music/AC-DC/1978 - If You Want Blood, You've Got It/06 - AC-DC - Whole Lotta Rosie.mp3;Whole Lotta Rosie;06;1978;Hard Rock;4:05
;3;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - If You Want Blood, You've Got It/05 - AC-DC - Problem Child.mp3;/music/AC-DC/1978 - If You Want Blood, You've Got It/05 - AC-DC - Problem Child.mp3;Problem Child;05;1978;Hard Rock;4:41
;3;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - If You Want Blood, You've Got It/07 - AC-DC - Rock 'N' Roll Damnation.mp3;/music/AC-DC/1978 - If You Want Blood, You've Got It/07 - AC-DC - Rock 'N' Roll Damnation.mp3;Rock 'N' Roll Damnation;07;1978;Hard Rock;3:41
;3;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - If You Want Blood, You've Got It/09 - AC-DC - Let There Be Rock.mp3;/music/AC-DC/1978 - If You Want Blood, You've Got It/09 - AC-DC - Let There Be Rock.mp3;Let There Be Rock;09;1978;Hard Rock;8:33
;3;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - If You Want Blood, You've Got It/08 - AC-DC - High Voltage.mp3;/music/AC-DC/1978 - If You Want Blood, You've Got It/08 - AC-DC - High Voltage.mp3;High Voltage;08;1978;Hard Rock;5:04
;3;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - If You Want Blood, You've Got It/02 - AC-DC - Hell Ain't a Bad Place To Be.mp3;/music/AC-DC/1978 - If You Want Blood, You've Got It/02 - AC-DC - Hell Ain't a Bad Place To Be.mp3;Hell Ain't a Bad Place To Be;02;1978;Hard Rock;4:10
;3;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - If You Want Blood, You've Got It/10 - AC-DC - Rocker.mp3;/music/AC-DC/1978 - If You Want Blood, You've Got It/10 - AC-DC - Rocker.mp3;Rocker;10;1978;Hard Rock;3:12
;3;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1978 - If You Want Blood, You've Got It/01 - AC-DC - Riff Raff.mp3;/music/AC-DC/1978 - If You Want Blood, You've Got It/01 - AC-DC - Riff Raff.mp3;Riff Raff;01;1978;Hard Rock;5:58
;4;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1984 - '74 Jailbreak/02 - AC-DC - You Ain't Got A Hold On Me.mp3;/music/AC-DC/1984 - '74 Jailbreak/02 - AC-DC - You Ain't Got A Hold On Me.mp3;You Ain't Got A Hold On Me;02;1984;Hard Rock;3:32
;4;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1984 - '74 Jailbreak/05 - AC-DC - Baby, Please Don't Go.mp3;/music/AC-DC/1984 - '74 Jailbreak/05 - AC-DC - Baby, Please Don't Go.mp3;Baby, Please Don't Go;05;1984;Hard Rock;5:00
;4;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1984 - '74 Jailbreak/04 - AC-DC - Soul Stripper.mp3;/music/AC-DC/1984 - '74 Jailbreak/04 - AC-DC - Soul Stripper.mp3;Soul Stripper;04;1984;Hard Rock;6:25
;4;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1984 - '74 Jailbreak/01 - AC-DC - Jailbreak.mp3;/music/AC-DC/1984 - '74 Jailbreak/01 - AC-DC - Jailbreak.mp3;Jailbreak;01;1984;Hard Rock;4:41
;4;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1984 - '74 Jailbreak/03 - AC-DC - Show Business.mp3;/music/AC-DC/1984 - '74 Jailbreak/03 - AC-DC - Show Business.mp3;Show Business;03;1984;Hard Rock;4:47
;5;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Volts/07 - AC-DC - She's Got Balls.mp3;/music/AC-DC/1997 - Volts/07 - AC-DC - She's Got Balls.mp3;She's Got Balls;07;1997;Hard Rock;7:56
;5;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Volts/05 - AC-DC - Get it Hot.mp3;/music/AC-DC/1997 - Volts/05 - AC-DC - Get it Hot.mp3;Get it Hot;05;1997;Hard Rock;4:15
;5;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Volts/01 - AC-DC - Dirty Eyes.mp3;/music/AC-DC/1997 - Volts/01 - AC-DC - Dirty Eyes.mp3;Dirty Eyes;01;1997;Hard Rock;3:21
;5;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Volts/08 - AC-DC - School Days.mp3;/music/AC-DC/1997 - Volts/08 - AC-DC - School Days.mp3;School Days;08;1997;Hard Rock;5:21
;5;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Volts/10 - AC-DC - Ride On.mp3;/music/AC-DC/1997 - Volts/10 - AC-DC - Ride On.mp3;Ride On;10;1997;Hard Rock;9:44
;5;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Volts/04 - AC-DC - Back Seat Confidential.mp3;/music/AC-DC/1997 - Volts/04 - AC-DC - Back Seat Confidential.mp3;Back Seat Confidential;04;1997;Hard Rock;5:24
;5;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Volts/06 - AC-DC -  Sin City.mp3;/music/AC-DC/1997 - Volts/06 - AC-DC -  Sin City.mp3;Sin City;06;1997;Hard Rock;4:54
;5;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Volts/03 - AC-DC - If You Want Blood You Got It.mp3;/music/AC-DC/1997 - Volts/03 - AC-DC - If You Want Blood You Got It.mp3;If You Want Blood You Got It;03;1997;Hard Rock;4:26
;5;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Volts/02 - AC-DC - Touch Too Much.mp3;/music/AC-DC/1997 - Volts/02 - AC-DC - Touch Too Much.mp3;Touch Too Much;02;1997;Hard Rock;6:34
;6;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Live from the Atlantic Studios/03 - AC -DC -  High Voltage.mp3;/music/AC-DC/1997 - Live from the Atlantic Studios/03 - AC -DC -  High Voltage.mp3;High Voltage;03;1997;Classic Rock;5:57
;6;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Live from the Atlantic Studios/06 - AC -DC -  The Jack.mp3;/music/AC-DC/1997 - Live from the Atlantic Studios/06 - AC -DC -  The Jack.mp3;The Jack;06;1997;Classic Rock;8:37
;6;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Live from the Atlantic Studios/08 - AC -DC -  Rocker.mp3;/music/AC-DC/1997 - Live from the Atlantic Studios/08 - AC -DC -  Rocker.mp3;Rocker;08;1997;Classic Rock;5:31
;6;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Live from the Atlantic Studios/01 - AC -DC - Live Wire.mp3;/music/AC-DC/1997 - Live from the Atlantic Studios/01 - AC -DC - Live Wire.mp3;Live Wire;01;1997;Classic Rock;6:17
;6;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Live from the Atlantic Studios/02 - AC -DC -  Problem Child.mp3;/music/AC-DC/1997 - Live from the Atlantic Studios/02 - AC -DC -  Problem Child.mp3;Problem Child;02;1997;Classic Rock;4:40
;6;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Live from the Atlantic Studios/04 - AC -DC -  Hell Ain't a Bad Place to Be.mp3;/music/AC-DC/1997 - Live from the Atlantic Studios/04 - AC -DC -  Hell Ain't a Bad Place to Be.mp3;Hell Ain't a Bad Place to Be;04;1997;Classic Rock;4:14
;6;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Live from the Atlantic Studios/07 - AC -DC -  Whole Lotta Rosie.mp3;/music/AC-DC/1997 - Live from the Atlantic Studios/07 - AC -DC -  Whole Lotta Rosie.mp3;Whole Lotta Rosie;07;1997;Classic Rock;5:11
;6;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Live from the Atlantic Studios/05 - AC -DC -  Dog Eat Dog.mp3;/music/AC-DC/1997 - Live from the Atlantic Studios/05 - AC -DC -  Dog Eat Dog.mp3;Dog Eat Dog;05;1997;Classic Rock;4:42
;7;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD2/05 - AC-DC - Whole Lotta Rosie.mp3;/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD2/05 - AC-DC - Whole Lotta Rosie.mp3;Whole Lotta Rosie;5;1997;Classic Rock;4:55
;7;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD2/04 - AC-DC - High Voltage.mp3;/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD2/04 - AC-DC - High Voltage.mp3;High Voltage;4;1997;Classic Rock;6:32
;7;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD2/03 - AC-DC - Girls Got Rhythm.mp3;/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD2/03 - AC-DC - Girls Got Rhythm.mp3;Girls Got Rhythm;3;1997;Classic Rock;3:20
;7;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD2/07 - AC-DC - T.N.T..mp3;/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD2/07 - AC-DC - T.N.T..mp3;T.N.T.;7;1997;Classic Rock;4:14
;7;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD2/06 - AC-DC - Rocker.mp3;/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD2/06 - AC-DC - Rocker.mp3;Rocker;6;1997;Classic Rock;10:45
;7;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD2/01 - AC-DC - The Jack.mp3;/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD2/01 - AC-DC - The Jack.mp3;The Jack;1;1997;Classic Rock;6:05
;7;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD2/02 - AC-DC - Highway to Hell.mp3;/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD2/02 - AC-DC - Highway to Hell.mp3;Highway to Hell;2;1997;Classic Rock;3:31
;8;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD1/05 - AC-DC - Walk All Over You.mp3;/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD1/05 - AC-DC - Walk All Over You.mp3;Walk All Over You;5;1997;Classic Rock;5:06
;8;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD1/04 - AC-DC - Sin City.mp3;/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD1/04 - AC-DC - Sin City.mp3;Sin City;4;1997;Classic Rock;5:25
;8;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD1/06 - AC-DC - Bad Boy Boogie.mp3;/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD1/06 - AC-DC - Bad Boy Boogie.mp3;Bad Boy Boogie;6;1997;Classic Rock;13:21
;8;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD1/01 - AC-DC - Live Wire.mp3;/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD1/01 - AC-DC - Live Wire.mp3;Live Wire;1;1997;Classic Rock;8:05
;8;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD1/03 - AC-DC - Hell Ain't a Bad Place to Be.mp3;/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD1/03 - AC-DC - Hell Ain't a Bad Place to Be.mp3;Hell Ain't a Bad Place to Be;3;1997;Classic Rock;4:32
;8;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD1/02 - AC-DC - Shot Down in Flames.mp3;/music/AC-DC/1997 - Let There Be Rock- The Movie (Live in Paris)/AC-DC - Let There Be Rock- The Movie (Live in Paris) CD1/02 - AC-DC - Shot Down in Flames.mp3;Shot Down in Flames;2;1997;Classic Rock;3:39
;9;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1975 - High Voltage (australian version)/05 - AC-DC - Soul Stripper.mp3;/music/AC-DC/1975 - High Voltage (australian version)/05 - AC-DC - Soul Stripper.mp3;Soul Stripper;05;1974;Hard Rock;6:25
;9;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1975 - High Voltage (australian version)/03 - AC-DC - Little Lover.mp3;/music/AC-DC/1975 - High Voltage (australian version)/03 - AC-DC - Little Lover.mp3;Little Lover;03;1974;Hard Rock;5:39
;9;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1975 - High Voltage (australian version)/01 - AC-DC - Baby, Please Don't Go.mp3;/music/AC-DC/1975 - High Voltage (australian version)/01 - AC-DC - Baby, Please Don't Go.mp3;Baby, Please Don't Go;01;1974;Hard Rock;4:51
;9;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1975 - High Voltage (australian version)/08 - AC-DC - Show Business.mp3;/music/AC-DC/1975 - High Voltage (australian version)/08 - AC-DC - Show Business.mp3;Show Business;08;1974;Hard Rock;4:46
;9;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1975 - High Voltage (australian version)/07 - AC-DC - Love Song.mp3;/music/AC-DC/1975 - High Voltage (australian version)/07 - AC-DC - Love Song.mp3;Love Song;07;1974;Hard Rock;5:18
;9;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1975 - High Voltage (australian version)/06 - AC-DC - You Ain't Got A Hold On Me.mp3;/music/AC-DC/1975 - High Voltage (australian version)/06 - AC-DC - You Ain't Got A Hold On Me.mp3;You Ain't Got A Hold On Me;06;1974;Hard Rock;3:33
;9;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1975 - High Voltage (australian version)/02 - AC-DC - She's Got Balls.mp3;/music/AC-DC/1975 - High Voltage (australian version)/02 - AC-DC - She's Got Balls.mp3;She's Got Balls;02;1974;Hard Rock;4:48
;9;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1975 - High Voltage (australian version)/04 - AC-DC -  Stick Around.mp3;/music/AC-DC/1975 - High Voltage (australian version)/04 - AC-DC -  Stick Around.mp3;Stick Around;04;1974;Hard Rock;4:39
;10;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1977 - Let There Be Rock/08 - AC-DC - Whole Lotta Rosie.mp3;/music/AC-DC/1977 - Let There Be Rock/08 - AC-DC - Whole Lotta Rosie.mp3;Whole Lotta Rosie;08;1977;Hard Rock;5:25
;10;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1977 - Let There Be Rock/05 - AC-DC - Overdose.mp3;/music/AC-DC/1977 - Let There Be Rock/05 - AC-DC - Overdose.mp3;Overdose;05;1977;Hard Rock;6:09
;10;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1977 - Let There Be Rock/07 - AC-DC - Hell Ain't A Bad Place To Be.mp3;/music/AC-DC/1977 - Let There Be Rock/07 - AC-DC - Hell Ain't A Bad Place To Be.mp3;Hell Ain't A Bad Place To Be;07;1977;Hard Rock;4:14
;10;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1977 - Let There Be Rock/03 - AC-DC - Let There Be Rock.mp3;/music/AC-DC/1977 - Let There Be Rock/03 - AC-DC - Let There Be Rock.mp3;Let There Be Rock;03;1977;Hard Rock;6:07
;10;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1977 - Let There Be Rock/02 - AC-DC - Dog Eat Dog.mp3;/music/AC-DC/1977 - Let There Be Rock/02 - AC-DC - Dog Eat Dog.mp3;Dog Eat Dog;02;1977;Hard Rock;3:35
;10;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1977 - Let There Be Rock/01 - AC-DC - Go Down.mp3;/music/AC-DC/1977 - Let There Be Rock/01 - AC-DC - Go Down.mp3;Go Down;01;1977;Hard Rock;5:31
;10;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1977 - Let There Be Rock/04 - AC-DC - Bad Boy Boogie.mp3;/music/AC-DC/1977 - Let There Be Rock/04 - AC-DC - Bad Boy Boogie.mp3;Bad Boy Boogie;04;1977;Hard Rock;4:27
;10;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1977 - Let There Be Rock/06 - AC-DC - Crabsody In Blue.mp3;/music/AC-DC/1977 - Let There Be Rock/06 - AC-DC - Crabsody In Blue.mp3;Crabsody In Blue;06;1977;Hard Rock;4:44
;11;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1979 - Highway To Hell/03 - AC-DC - Walk All Over You.mp3;/music/AC-DC/1979 - Highway To Hell/03 - AC-DC - Walk All Over You.mp3;Walk All Over You;03;1979;Hard Rock;5:10
;11;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1979 - Highway To Hell/04 - AC-DC - Touch Too Much.mp3;/music/AC-DC/1979 - Highway To Hell/04 - AC-DC - Touch Too Much.mp3;Touch Too Much;04;1979;Hard Rock;4:26
;11;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1979 - Highway To Hell/09 - AC-DC - Love Hungry Man.mp3;/music/AC-DC/1979 - Highway To Hell/09 - AC-DC - Love Hungry Man.mp3;Love Hungry Man;09;1979;Hard Rock;4:17
;11;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1979 - Highway To Hell/02 - AC-DC - Girls Got Rhythm.mp3;/music/AC-DC/1979 - Highway To Hell/02 - AC-DC - Girls Got Rhythm.mp3;Girls Got Rhythm;02;1979;Hard Rock;3:23
;11;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1979 - Highway To Hell/01 - AC-DC - Highway To Hell.mp3;/music/AC-DC/1979 - Highway To Hell/01 - AC-DC - Highway To Hell.mp3;Highway To Hell;01;1979;Hard Rock;3:28
;11;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1979 - Highway To Hell/07 - AC-DC - Get It Hot.mp3;/music/AC-DC/1979 - Highway To Hell/07 - AC-DC - Get It Hot.mp3;Get It Hot;07;1979;Hard Rock;2:35
;11;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1979 - Highway To Hell/05 - AC-DC - Beating Around The Bush.mp3;/music/AC-DC/1979 - Highway To Hell/05 - AC-DC - Beating Around The Bush.mp3;Beating Around The Bush;05;1979;Hard Rock;3:56
;11;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1979 - Highway To Hell/08 - AC-DC - If You Want Blood (You've Got It).mp3;/music/AC-DC/1979 - Highway To Hell/08 - AC-DC - If You Want Blood (You've Got It).mp3;If You Want Blood (You've Got It);08;1979;Hard Rock;4:37
;11;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1979 - Highway To Hell/10 - AC-DC - Night Prowler.mp3;/music/AC-DC/1979 - Highway To Hell/10 - AC-DC - Night Prowler.mp3;Night Prowler;10;1979;Hard Rock;6:28
;11;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1979 - Highway To Hell/06 - AC-DC - Shot Down In Flames.mp3;/music/AC-DC/1979 - Highway To Hell/06 - AC-DC - Shot Down In Flames.mp3;Shot Down In Flames;06;1979;Hard Rock;3:23
;12;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/12 - AC-DC - Moneytalks [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/12 - AC-DC - Moneytalks [Live].mp3;Moneytalks [Live];12;1992;Hard Rock;4:30
;12;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/07 - AC-DC - Fire Your Guns [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/07 - AC-DC - Fire Your Guns [Live].mp3;Fire Your Guns [Live];07;1992;Hard Rock;3:41
;12;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/05 - AC-DC - Who Made Who [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/05 - AC-DC - Who Made Who [Live].mp3;Who Made Who [Live];05;1992;Hard Rock;5:16
;12;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/10 - AC-DC - The Razors Edge [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/10 - AC-DC - The Razors Edge [Live].mp3;The Razors Edge [Live];10;1992;Hard Rock;4:36
;12;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/03 - AC-DC - Back In Black [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/03 - AC-DC - Back In Black [Live].mp3;Back In Black [Live];03;1992;Hard Rock;4:28
;12;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/11 - AC-DC - Dirty Deeds Done Dirt Cheap [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/11 - AC-DC - Dirty Deeds Done Dirt Cheap [Live].mp3;Dirty Deeds Done Dirt Cheap [Live];11;1992;Hard Rock;5:03
;12;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/06 - AC-DC - Heatseeker [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/06 - AC-DC - Heatseeker [Live].mp3;Heatseeker [Live];06;1992;Hard Rock;3:37
;12;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/02 - AC-DC - Shoot To Thrill [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/02 - AC-DC - Shoot To Thrill [Live].mp3;Shoot To Thrill [Live];02;1992;Hard Rock;5:23
;12;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/04 - AC-DC - Sin City [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/04 - AC-DC - Sin City [Live].mp3;Sin City [Live];04;1992;Hard Rock;5:41
;12;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/09 - AC-DC - The Jack [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/09 - AC-DC - The Jack [Live].mp3;The Jack [Live];09;1992;Hard Rock;6:58
;12;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/01 - AC-DC - Thunderstruck [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/01 - AC-DC - Thunderstruck [Live].mp3;Thunderstruck [Live];01;1992;Hard Rock;6:35
;12;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/08 - AC-DC - Jailbreak [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 1]/08 - AC-DC - Jailbreak [Live].mp3;Jailbreak [Live];08;1992;Hard Rock;14:43
;13;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/08 - AC-DC - Bonny [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/08 - AC-DC - Bonny [Live].mp3;Bonny [Live];08;1992;Hard Rock;1:03
;13;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/01 - AC-DC - Hells Bells [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/01 - AC-DC - Hells Bells [Live].mp3;Hells Bells [Live];01;1992;Hard Rock;6:01
;13;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/05 - AC-DC - You Shook Me All Night Long [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/05 - AC-DC - You Shook Me All Night Long [Live].mp3;You Shook Me All Night Long [Live];05;1992;Hard Rock;3:55
;13;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/06 - AC-DC - Whole Lotta Rosie [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/06 - AC-DC - Whole Lotta Rosie [Live].mp3;Whole Lotta Rosie [Live];06;1992;Hard Rock;4:31
;13;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/03 - AC-DC - That's The Way I Wanna Rock N Roll [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/03 - AC-DC - That's The Way I Wanna Rock N Roll [Live].mp3;That's The Way I Wanna Rock N Roll [Live];03;1992;Hard Rock;3:57
;13;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/11 - AC-DC - For Those About To Rock (We Salute You) [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/11 - AC-DC - For Those About To Rock (We Salute You) [Live].mp3;For Those About To Rock (We Salute You) [Live];11;1992;Hard Rock;7:18
;13;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/04 - AC-DC - High Voltage [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/04 - AC-DC - High Voltage [Live].mp3;High Voltage [Live];04;1992;Hard Rock;10:33
;13;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/02 - AC-DC - Are You Ready [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/02 - AC-DC - Are You Ready [Live].mp3;Are You Ready [Live];02;1992;Hard Rock;4:34
;13;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/09 - AC-DC - Highway To Hell [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/09 - AC-DC - Highway To Hell [Live].mp3;Highway To Hell [Live];09;1992;Hard Rock;3:54
;13;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/07 - AC-DC - Let There Be Rock [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/07 - AC-DC - Let There Be Rock [Live].mp3;Let There Be Rock [Live];07;1992;Hard Rock;12:17
;13;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/10 - AC-DC - T.N.T. [Live].mp3;/music/AC-DC/1992 - Live- Collector's Edition/AC-DC - AC-DC Live- Collector's Edition [Disc 2]/10 - AC-DC - T.N.T. [Live].mp3;T.N.T. [Live];10;1992;Hard Rock;3:48
;14;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1981 - For Those About To Rock We Salute You/07 - AC-DC - C.O.D.mp3;/music/AC-DC/1981 - For Those About To Rock We Salute You/07 - AC-DC - C.O.D.mp3;C.O.D;07;1981;Hard Rock;3:20
;14;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1981 - For Those About To Rock We Salute You/01 - AC-DC - For Those About To Rock (We Salute You).mp3;/music/AC-DC/1981 - For Those About To Rock We Salute You/01 - AC-DC - For Those About To Rock (We Salute You).mp3;For Those About To Rock (We Salute You);01;1981;Hard Rock;5:44
;14;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1981 - For Those About To Rock We Salute You/09 - AC-DC - Night Of The Long Knives.mp3;/music/AC-DC/1981 - For Those About To Rock We Salute You/09 - AC-DC - Night Of The Long Knives.mp3;Night Of The Long Knives;09;1981;Hard Rock;3:26
;14;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1981 - For Those About To Rock We Salute You/08 - AC-DC - Breaking The Rules.mp3;/music/AC-DC/1981 - For Those About To Rock We Salute You/08 - AC-DC - Breaking The Rules.mp3;Breaking The Rules;08;1981;Hard Rock;4:23
;14;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1981 - For Those About To Rock We Salute You/03 - AC-DC - Let's Get It Up.mp3;/music/AC-DC/1981 - For Those About To Rock We Salute You/03 - AC-DC - Let's Get It Up.mp3;Let's Get It Up;03;1981;Hard Rock;3:54
;14;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1981 - For Those About To Rock We Salute You/10 - AC-DC - Spellbound.mp3;/music/AC-DC/1981 - For Those About To Rock We Salute You/10 - AC-DC - Spellbound.mp3;Spellbound;10;1981;Hard Rock;4:39
;14;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1981 - For Those About To Rock We Salute You/06 - AC-DC - Evil Walks.mp3;/music/AC-DC/1981 - For Those About To Rock We Salute You/06 - AC-DC - Evil Walks.mp3;Evil Walks;06;1981;Hard Rock;4:24
;14;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1981 - For Those About To Rock We Salute You/02 - AC-DC - Put The Finger On You.mp3;/music/AC-DC/1981 - For Those About To Rock We Salute You/02 - AC-DC - Put The Finger On You.mp3;Put The Finger On You;02;1981;Hard Rock;3:26
;14;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1981 - For Those About To Rock We Salute You/04 - AC-DC - Inject The Venom.mp3;/music/AC-DC/1981 - For Those About To Rock We Salute You/04 - AC-DC - Inject The Venom.mp3;Inject The Venom;04;1981;Hard Rock;3:31
;14;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1981 - For Those About To Rock We Salute You/05 - AC-DC - Snowballed.mp3;/music/AC-DC/1981 - For Those About To Rock We Salute You/05 - AC-DC - Snowballed.mp3;Snowballed;05;1981;Hard Rock;3:23
;15;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1985 - Fly On The Wall/10 - AC-DC - Send For The Man.mp3;/music/AC-DC/1985 - Fly On The Wall/10 - AC-DC - Send For The Man.mp3;Send For The Man;10;1985;Hard Rock;3:37
;15;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1985 - Fly On The Wall/05 - AC-DC - Sink The Pink.mp3;/music/AC-DC/1985 - Fly On The Wall/05 - AC-DC - Sink The Pink.mp3;Sink The Pink;05;1985;Hard Rock;4:15
;15;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1985 - Fly On The Wall/06 - AC-DC - Playing With Girls.mp3;/music/AC-DC/1985 - Fly On The Wall/06 - AC-DC - Playing With Girls.mp3;Playing With Girls;06;1985;Hard Rock;3:45
;15;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1985 - Fly On The Wall/02 - AC-DC - Shake Your Foundations.mp3;/music/AC-DC/1985 - Fly On The Wall/02 - AC-DC - Shake Your Foundations.mp3;Shake Your Foundations;02;1985;Hard Rock;4:11
;15;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1985 - Fly On The Wall/01 - AC-DC - Fly On The Wall.mp3;/music/AC-DC/1985 - Fly On The Wall/01 - AC-DC - Fly On The Wall.mp3;Fly On The Wall;01;1985;Hard Rock;3:44
;15;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1985 - Fly On The Wall/07 - AC-DC - Stand Up.mp3;/music/AC-DC/1985 - Fly On The Wall/07 - AC-DC - Stand Up.mp3;Stand Up;07;1985;Hard Rock;3:53
;15;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1985 - Fly On The Wall/09 - AC-DC - Back In Business.mp3;/music/AC-DC/1985 - Fly On The Wall/09 - AC-DC - Back In Business.mp3;Back In Business;09;1985;Hard Rock;4:24
;15;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1985 - Fly On The Wall/04 - AC-DC - Danger.mp3;/music/AC-DC/1985 - Fly On The Wall/04 - AC-DC - Danger.mp3;Danger;04;1985;Hard Rock;4:23
;15;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1985 - Fly On The Wall/03 - AC-DC - First Blood.mp3;/music/AC-DC/1985 - Fly On The Wall/03 - AC-DC - First Blood.mp3;First Blood;03;1985;Hard Rock;3:46
;15;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1985 - Fly On The Wall/08 - AC-DC - Hell Or High Water.mp3;/music/AC-DC/1985 - Fly On The Wall/08 - AC-DC - Hell Or High Water.mp3;Hell Or High Water;08;1985;Hard Rock;4:32
;16;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1990 - The Razor's Edge/05-AC-DC - mistress for christmas.mp3;/music/AC-DC/1990 - The Razor's Edge/05-AC-DC - mistress for christmas.mp3;Mistress For Christmas;05;1990;Hard Rock;4:00
;16;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1990 - The Razor's Edge/09-AC-DC - shot of love.mp3;/music/AC-DC/1990 - The Razor's Edge/09-AC-DC - shot of love.mp3;Shot Of Love;09;1990;Hard Rock;3:57
;16;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1990 - The Razor's Edge/06-AC-DC - rock your heart out.mp3;/music/AC-DC/1990 - The Razor's Edge/06-AC-DC - rock your heart out.mp3;Rock Your Heart Out;06;1990;Hard Rock;4:07
;16;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1990 - The Razor's Edge/11-AC-DC - goodbye and good riddance  to bad luck.mp3;/music/AC-DC/1990 - The Razor's Edge/11-AC-DC - goodbye and good riddance  to bad luck.mp3;Goodbye And Good Riddance To B;11;1990;Hard Rock;3:14
;16;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1990 - The Razor's Edge/08-AC-DC - got you  by the balls.mp3;/music/AC-DC/1990 - The Razor's Edge/08-AC-DC - got you  by the balls.mp3;Got You By The Balls;08;1990;Hard Rock;4:30
;16;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1990 - The Razor's Edge/02-AC-DC - fire your guns.mp3;/music/AC-DC/1990 - The Razor's Edge/02-AC-DC - fire your guns.mp3;Fire Your Guns;02;1990;Hard Rock;2:54
;16;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1990 - The Razor's Edge/03-AC-DC - moneytalks.mp3;/music/AC-DC/1990 - The Razor's Edge/03-AC-DC - moneytalks.mp3;Moneytalks;03;1990;Hard Rock;3:46
;16;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1990 - The Razor's Edge/12-AC-DC - if you dare.mp3;/music/AC-DC/1990 - The Razor's Edge/12-AC-DC - if you dare.mp3;If You Dare;12;1990;Hard Rock;3:18
;16;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1990 - The Razor's Edge/07-AC-DC - are you ready.mp3;/music/AC-DC/1990 - The Razor's Edge/07-AC-DC - are you ready.mp3;Are You Ready;07;1990;Hard Rock;4:10
;16;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1990 - The Razor's Edge/04-AC-DC - the razors edge.mp3;/music/AC-DC/1990 - The Razor's Edge/04-AC-DC - the razors edge.mp3;The Razor's Edge;04;1990;Hard Rock;4:23
;16;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1990 - The Razor's Edge/10-AC-DC - let's make it.mp3;/music/AC-DC/1990 - The Razor's Edge/10-AC-DC - let's make it.mp3;Let's Make It;10;1990;Hard Rock;3:32
;16;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1990 - The Razor's Edge/01-AC-DC - thunderstruck.mp3;/music/AC-DC/1990 - The Razor's Edge/01-AC-DC - thunderstruck.mp3;Thunderstruck;01;1990;Hard Rock;4:53
;17;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1986 - Who Made Who/03 - AC-DC - d.t..mp3;/music/AC-DC/1986 - Who Made Who/03 - AC-DC - d.t..mp3;D.T.;03;1986;Hard Rock;2:54
;17;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1986 - Who Made Who/01 - AC-DC - who made  who.mp3;/music/AC-DC/1986 - Who Made Who/01 - AC-DC - who made  who.mp3;Who Made Who;01;1986;Hard Rock;3:27
;17;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1986 - Who Made Who/06 - AC-DC - hells bells.mp3;/music/AC-DC/1986 - Who Made Who/06 - AC-DC - hells bells.mp3;Hells Bells;06;1986;Hard Rock;5:13
;17;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1986 - Who Made Who/09 - AC-DC - for those about to rock (we salute you).mp3;/music/AC-DC/1986 - Who Made Who/09 - AC-DC - for those about to rock (we salute you).mp3;For Those About To Rock(We Sa;09;1986;Hard Rock;5:54
;17;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1986 - Who Made Who/02 - AC-DC - you shook me all night long.mp3;/music/AC-DC/1986 - Who Made Who/02 - AC-DC - you shook me all night long.mp3;You Shook Me All Night Long;02;1986;Hard Rock;3:31
;17;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1986 - Who Made Who/05 - AC-DC - ride on.mp3;/music/AC-DC/1986 - Who Made Who/05 - AC-DC - ride on.mp3;Ride On;05;1986;Hard Rock;5:51
;17;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1986 - Who Made Who/08 - AC-DC - chase the ace.mp3;/music/AC-DC/1986 - Who Made Who/08 - AC-DC - chase the ace.mp3;Chase The Ace;08;1986;Hard Rock;3:01
;17;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1986 - Who Made Who/07 - AC-DC - shake your foundations.mp3;/music/AC-DC/1986 - Who Made Who/07 - AC-DC - shake your foundations.mp3;Shake Your Foundations;07;1986;Hard Rock;3:54
;17;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1986 - Who Made Who/04 - AC-DC - sink the pink.mp3;/music/AC-DC/1986 - Who Made Who/04 - AC-DC - sink the pink.mp3;Sink The Pink;04;1986;Hard Rock;4:13
;18;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1995 - Ballbreaker/01 - AC-DC - Hard As A Rock.mp3;/music/AC-DC/1995 - Ballbreaker/01 - AC-DC - Hard As A Rock.mp3;Hard As A Rock;01;1995;Hard Rock;4:31
;18;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1995 - Ballbreaker/08 - AC-DC - Love Bomb.mp3;/music/AC-DC/1995 - Ballbreaker/08 - AC-DC - Love Bomb.mp3;Love Bomb;08;1995;Hard Rock;3:14
;18;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1995 - Ballbreaker/03 - AC-DC - The Furor.mp3;/music/AC-DC/1995 - Ballbreaker/03 - AC-DC - The Furor.mp3;The Furor;03;1995;Hard Rock;4:11
;18;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1995 - Ballbreaker/10 - AC-DC - Whiskey On The Rocks.mp3;/music/AC-DC/1995 - Ballbreaker/10 - AC-DC - Whiskey On The Rocks.mp3;Whiskey On The Rocks;10;1995;Hard Rock;4:35
;18;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1995 - Ballbreaker/05 - AC-DC - Honey Roll.mp3;/music/AC-DC/1995 - Ballbreaker/05 - AC-DC - Honey Roll.mp3;Honey Roll;05;1995;Hard Rock;5:35
;18;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1995 - Ballbreaker/07 - AC-DC - Hail Caesar.mp3;/music/AC-DC/1995 - Ballbreaker/07 - AC-DC - Hail Caesar.mp3;Hail Caesar;07;1995;Hard Rock;5:14
;18;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1995 - Ballbreaker/02 - AC-DC - Cover You In Oil.mp3;/music/AC-DC/1995 - Ballbreaker/02 - AC-DC - Cover You In Oil.mp3;Cover You In Oil;02;1995;Hard Rock;4:33
;18;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1995 - Ballbreaker/11 - AC-DC - Ball Breaker.mp3;/music/AC-DC/1995 - Ballbreaker/11 - AC-DC - Ball Breaker.mp3;Ball Breaker;11;1995;Hard Rock;4:52
;18;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1995 - Ballbreaker/09 - AC-DC - Caught With Your Pants Down.mp3;/music/AC-DC/1995 - Ballbreaker/09 - AC-DC - Caught With Your Pants Down.mp3;Caught With Your Pants Down;09;1995;Hard Rock;4:15
;18;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1995 - Ballbreaker/04 - AC-DC - Boogie Man.mp3;/music/AC-DC/1995 - Ballbreaker/04 - AC-DC - Boogie Man.mp3;Boogie Man;04;1995;Hard Rock;4:07
;18;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1995 - Ballbreaker/06 - AC-DC - Burnin' Alive.mp3;/music/AC-DC/1995 - Ballbreaker/06 - AC-DC - Burnin' Alive.mp3;Burnin' Alive;06;1995;Hard Rock;5:05
;19;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1983 - Flick Of The Switch/09 - AC-DC - Badlands.mp3;/music/AC-DC/1983 - Flick Of The Switch/09 - AC-DC - Badlands.mp3;Badlands;09;1983;Hard Rock;3:39
;19;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1983 - Flick Of The Switch/02 - AC-DC - This House Is On Fire.mp3;/music/AC-DC/1983 - Flick Of The Switch/02 - AC-DC - This House Is On Fire.mp3;This House Is On Fire;02;1983;Hard Rock;3:24
;19;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1983 - Flick Of The Switch/10 - AC-DC - Brain Shake.mp3;/music/AC-DC/1983 - Flick Of The Switch/10 - AC-DC - Brain Shake.mp3;Brain Shake;10;1983;Hard Rock;4:09
;19;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1983 - Flick Of The Switch/03 - AC-DC - Flick Of The Switch.mp3;/music/AC-DC/1983 - Flick Of The Switch/03 - AC-DC - Flick Of The Switch.mp3;Flick Of The Switch;03;1983;Hard Rock;3:14
;19;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1983 - Flick Of The Switch/05 - AC-DC - Landslide.mp3;/music/AC-DC/1983 - Flick Of The Switch/05 - AC-DC - Landslide.mp3;Landslide;05;1983;Hard Rock;3:58
;19;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1983 - Flick Of The Switch/07 - AC-DC - Deep In The Hole.mp3;/music/AC-DC/1983 - Flick Of The Switch/07 - AC-DC - Deep In The Hole.mp3;Deep In The Hole;07;1983;Hard Rock;3:20
;19;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1983 - Flick Of The Switch/08 - AC-DC - Bedlam In Belgium.mp3;/music/AC-DC/1983 - Flick Of The Switch/08 - AC-DC - Bedlam In Belgium.mp3;Bedlam In Belgium;08;1983;Hard Rock;3:52
;19;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1983 - Flick Of The Switch/06 - AC-DC - Guns For Hire.mp3;/music/AC-DC/1983 - Flick Of The Switch/06 - AC-DC - Guns For Hire.mp3;Guns For Hire;06;1983;Hard Rock;3:25
;19;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1983 - Flick Of The Switch/01 - AC-DC - Rising Power.mp3;/music/AC-DC/1983 - Flick Of The Switch/01 - AC-DC - Rising Power.mp3;Rising Power;01;1983;Hard Rock;3:44
;19;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1983 - Flick Of The Switch/04 - AC-DC - Nervous Shakedown.mp3;/music/AC-DC/1983 - Flick Of The Switch/04 - AC-DC - Nervous Shakedown.mp3;Nervous Shakedown;04;1983;Hard Rock;4:27
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/08 - AC-DC - Ride On.mp3;/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/08 - AC-DC - Ride On.mp3;Ride On;08;1976;Hard Rock;5:51
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/06 - AC-DC - Big Balls.mp3;/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/06 - AC-DC - Big Balls.mp3;Big Balls;06;1976;Hard Rock;2:39
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/03 - AC-DC - There's Gonna Be Some Rockin'.mp3;/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/03 - AC-DC - There's Gonna Be Some Rockin'.mp3;There's Gonna Be Some Rockin';03;1976;Hard Rock;3:18
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/09 - AC-DC - Jailbreak.mp3;/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/09 - AC-DC - Jailbreak.mp3;Jailbreak;09;1976;Hard Rock;4:42
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/04 - AC-DC - Problem Child.mp3;/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/04 - AC-DC - Problem Child.mp3;Problem Child;04;1976;Hard Rock;5:50
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/05 - AC-DC - Squealer.mp3;/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/05 - AC-DC - Squealer.mp3;Squealer;05;1976;Hard Rock;5:18
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/02 - AC-DC - Ain't No Fun (Waiting 'Round To Be A Millionaire).mp3;/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/02 - AC-DC - Ain't No Fun (Waiting 'Round To Be A Millionaire).mp3;Ain't No Fun (Waiting 'Round To Be A Millionaire);02;1976;Hard Rock;7:31
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/01 - AC-DC - Dirty Deeds Done Dirt Cheap.mp3;/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/01 - AC-DC - Dirty Deeds Done Dirt Cheap.mp3;Dirty Deeds Done Dirt Cheap;01;1976;Hard Rock;4:14
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/07 - AC-DC - R.I.P. (Rock In Peace).mp3;/music/AC-DC/1976 - Dirty Deeds  Done Dirt Cheap (Australian Version)/07 - AC-DC - R.I.P. (Rock In Peace).mp3;R.I.P. (Rock In Peace);07;1976;Hard Rock;3:35
;21;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1980 - Back in Black/01 - AC-DC - Hells Bells.mp3;/music/AC-DC/1980 - Back in Black/01 - AC-DC - Hells Bells.mp3;Hells Bells;01;1980;Hard Rock;5:12
;21;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1980 - Back in Black/07 - AC-DC - You Shook Me All Night Long.mp3;/music/AC-DC/1980 - Back in Black/07 - AC-DC - You Shook Me All Night Long.mp3;You Shook Me All Night Long;07;1980;Hard Rock;3:30
;21;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1980 - Back in Black/02 - AC-DC - Shoot to Thrill.mp3;/music/AC-DC/1980 - Back in Black/02 - AC-DC - Shoot to Thrill.mp3;Shoot to Thrill;02;1980;Hard Rock;5:18
;21;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1980 - Back in Black/05 - AC-DC - Let Me Put My Love into You.mp3;/music/AC-DC/1980 - Back in Black/05 - AC-DC - Let Me Put My Love into You.mp3;Let Me Put My Love into You;05;1980;Hard Rock;4:16
;21;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1980 - Back in Black/03 - AC-DC - What Do You Do for Money Honey.mp3;/music/AC-DC/1980 - Back in Black/03 - AC-DC - What Do You Do for Money Honey.mp3;What Do You Do for Money Honey;03;1980;Hard Rock;3:35
;21;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1980 - Back in Black/08 - AC-DC - Have a Drink on Me.mp3;/music/AC-DC/1980 - Back in Black/08 - AC-DC - Have a Drink on Me.mp3;Have a Drink on Me;08;1980;Hard Rock;3:59
;21;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1980 - Back in Black/10 - AC-DC - Rock and Roll Ain't Noise Pollution.mp3;/music/AC-DC/1980 - Back in Black/10 - AC-DC - Rock and Roll Ain't Noise Pollution.mp3;Rock and Roll Ain't Noise Poll;10;1980;Hard Rock;4:26
;21;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1980 - Back in Black/09 - AC-DC - Shake a Leg.mp3;/music/AC-DC/1980 - Back in Black/09 - AC-DC - Shake a Leg.mp3;Shake a Leg;09;1980;Hard Rock;4:06
;21;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1980 - Back in Black/06 - AC-DC - Back in Black.mp3;/music/AC-DC/1980 - Back in Black/06 - AC-DC - Back in Black.mp3;Back in Black;06;1980;Hard Rock;4:15
;21;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1980 - Back in Black/04 - AC-DC - Givin the Dog a Bone.mp3;/music/AC-DC/1980 - Back in Black/04 - AC-DC - Givin the Dog a Bone.mp3;Givin the Dog a Bone;04;1980;Hard Rock;3:32
;22;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - High Voltage/09 - AC-DC - High Voltage.mp3;/music/AC-DC/1976 - High Voltage/09 - AC-DC - High Voltage.mp3;High Voltage;09;1976;Hard Rock;4:14
;22;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - High Voltage/04 - AC-DC - Live Wire.mp3;/music/AC-DC/1976 - High Voltage/04 - AC-DC - Live Wire.mp3;Live Wire;04;1976;Hard Rock;5:50
;22;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - High Voltage/05 - AC-DC - T.N.T.mp3;/music/AC-DC/1976 - High Voltage/05 - AC-DC - T.N.T.mp3;T.N.T;05;1976;Hard Rock;3:35
;22;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - High Voltage/02 - AC-DC - Rock 'n' Roll Singer.mp3;/music/AC-DC/1976 - High Voltage/02 - AC-DC - Rock 'n' Roll Singer.mp3;Rock 'n' Roll Singer;02;1976;Hard Rock;5:04
;22;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - High Voltage/08 - AC-DC - She's Got Balls.mp3;/music/AC-DC/1976 - High Voltage/08 - AC-DC - She's Got Balls.mp3;She's Got Balls;08;1976;Hard Rock;4:52
;22;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - High Voltage/06 - AC-DC - Can I Sit Next To You Girl.mp3;/music/AC-DC/1976 - High Voltage/06 - AC-DC - Can I Sit Next To You Girl.mp3;Can I Sit Next To You Girl;06;1976;Hard Rock;4:12
;22;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - High Voltage/07 - AC-DC - Little Lover.mp3;/music/AC-DC/1976 - High Voltage/07 - AC-DC - Little Lover.mp3;Little Lover;07;1976;Hard Rock;5:40
;22;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - High Voltage/01 - AC-DC - It's A Long Way To The Top (If You Wanna Rock 'N' Roll).mp3;/music/AC-DC/1976 - High Voltage/01 - AC-DC - It's A Long Way To The Top (If You Wanna Rock 'N' Roll).mp3;It's A Long Way To The Top (If You Wanna Rock 'N' Roll);01;1976;Hard Rock;5:02
;22;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - High Voltage/03 - AC-DC - The Jack.mp3;/music/AC-DC/1976 - High Voltage/03 - AC-DC - The Jack.mp3;The Jack;03;1976;Hard Rock;5:53
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/08 - AC-DC - Ride On.mp3;/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/08 - AC-DC - Ride On.mp3;Ride On;08;1981;Hard Rock;5:54
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/05 - AC-DC - Problem Child.mp3;/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/05 - AC-DC - Problem Child.mp3;Problem Child;05;1981;Hard Rock;5:47
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/04 - AC-DC - Rocker.mp3;/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/04 - AC-DC - Rocker.mp3;Rocker;04;1981;Hard Rock;2:52
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/09 - AC-DC - Squealer.mp3;/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/09 - AC-DC - Squealer.mp3;Squealer;09;1981;Hard Rock;5:28
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/03 - AC-DC - Big Balls.mp3;/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/03 - AC-DC - Big Balls.mp3;Big Balls;03;1981;Hard Rock;2:39
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/02 - AC-DC - Love At First Feel.mp3;/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/02 - AC-DC - Love At First Feel.mp3;Love At First Feel;02;1981;Hard Rock;3:13
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/07 - AC-DC - Ain't No Fun (Waiting Round To Be A Millionaire).mp3;/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/07 - AC-DC - Ain't No Fun (Waiting Round To Be A Millionaire).mp3;Ain't No Fun (Waiting Round To Be A Millionaire);07;1981;Hard Rock;6:58
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/06 - AC-DC - There's Gonna Be Some Rockin'.mp3;/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/06 - AC-DC - There's Gonna Be Some Rockin'.mp3;There's Gonna Be Some Rockin';06;1981;Hard Rock;3:18
;20;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/01 - AC-DC - Dirty Deeds Done Dirt Cheap.mp3;/music/AC-DC/1976 - Dirty Deeds Done Dirt Cheap/01 - AC-DC - Dirty Deeds Done Dirt Cheap.mp3;Dirty Deeds Done Dirt Cheap;01;1981;Hard Rock;3:52
;23;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1975 - T.N.T/05 - AC-DC - High Voltage.mp3;/music/AC-DC/1975 - T.N.T/05 - AC-DC - High Voltage.mp3;High Voltage;;1975;Hard Rock;4:24
;23;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1975 - T.N.T/04 - AC-DC - Live Wire.mp3;/music/AC-DC/1975 - T.N.T/04 - AC-DC - Live Wire.mp3;Live Wire;;1975;Hard Rock;6:21
;23;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1975 - T.N.T/06 - AC-DC - Rocker.mp3;/music/AC-DC/1975 - T.N.T/06 - AC-DC - Rocker.mp3;Rocker;;1975;Hard Rock;3:05
;23;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1975 - T.N.T/07 - AC-DC - Can I Sit Next To You Girl.mp3;/music/AC-DC/1975 - T.N.T/07 - AC-DC - Can I Sit Next To You Girl.mp3;Can I Sit Next To You Girl;;1975;Hard Rock;4:34
;23;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1975 - T.N.T/03 - AC-DC - T.N.T.mp3;/music/AC-DC/1975 - T.N.T/03 - AC-DC - T.N.T.mp3;T.N.T.;;1975;Hard Rock;3:53
;23;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1975 - T.N.T/09 - AC-DC - School Days.mp3;/music/AC-DC/1975 - T.N.T/09 - AC-DC - School Days.mp3;School Days;;1975;Hard Rock;5:52
;23;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1975 - T.N.T/08 - AC-DC - Rock n Roll Singer.mp3;/music/AC-DC/1975 - T.N.T/08 - AC-DC - Rock n Roll Singer.mp3;Rock 'n' Roll Singer;;1975;Hard Rock;5:30
;23;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1975 - T.N.T/02 - AC-DC - The Jack.mp3;/music/AC-DC/1975 - T.N.T/02 - AC-DC - The Jack.mp3;The Jack;;1975;Hard Rock;6:23
;23;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1975 - T.N.T/01 - AC-DC - Its A Long Way To The Top.mp3;/music/AC-DC/1975 - T.N.T/01 - AC-DC - Its A Long Way To The Top.mp3;It's A Long Way To The Top;;1975;Hard Rock;5:43
;24;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1988 - Blow Up Your Video/05 - AC-DC - Kissin' Dynamite.mp3;/music/AC-DC/1988 - Blow Up Your Video/05 - AC-DC - Kissin' Dynamite.mp3;Kissin' Dynamite;05;1988;Hard Rock;3:58
;24;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1988 - Blow Up Your Video/10 - AC-DC - This Means War.mp3;/music/AC-DC/1988 - Blow Up Your Video/10 - AC-DC - This Means War.mp3;This Means War;10;1988;Hard Rock;4:32
;24;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1988 - Blow Up Your Video/04 - AC-DC - Go Zone.mp3;/music/AC-DC/1988 - Blow Up Your Video/04 - AC-DC - Go Zone.mp3;Go Zone;04;1988;Hard Rock;4:27
;24;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1988 - Blow Up Your Video/01 - AC-DC - Heatseeker.mp3;/music/AC-DC/1988 - Blow Up Your Video/01 - AC-DC - Heatseeker.mp3;Heatseeker;01;1988;Hard Rock;3:50
;24;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1988 - Blow Up Your Video/06 - AC-DC - Nick Of Time.mp3;/music/AC-DC/1988 - Blow Up Your Video/06 - AC-DC - Nick Of Time.mp3;Nick Of Time;06;1988;Hard Rock;4:16
;24;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1988 - Blow Up Your Video/08 - AC-DC - Ruff Stuff.mp3;/music/AC-DC/1988 - Blow Up Your Video/08 - AC-DC - Ruff Stuff.mp3;Ruff Stuff;08;1988;Hard Rock;4:29
;24;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1988 - Blow Up Your Video/09 - AC-DC - Two's Up.mp3;/music/AC-DC/1988 - Blow Up Your Video/09 - AC-DC - Two's Up.mp3;Two's Up;09;1988;Hard Rock;5:20
;24;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1988 - Blow Up Your Video/07 - AC-DC - Some Sin For Nuthin'.mp3;/music/AC-DC/1988 - Blow Up Your Video/07 - AC-DC - Some Sin For Nuthin'.mp3;Some Sin For Nuthin';07;1988;Hard Rock;4:11
;24;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1988 - Blow Up Your Video/03 - AC-DC - Meanstreak.mp3;/music/AC-DC/1988 - Blow Up Your Video/03 - AC-DC - Meanstreak.mp3;Meanstreak;03;1988;Hard Rock;4:08
;24;1;/home/lpa/atinfo/www/soonic-upgrade/soonic/public/music/AC-DC/1988 - Blow Up Your Video/02 - AC-DC - That's The Way I Wanna Rock 'n' Roll.mp3;/music/AC-DC/1988 - Blow Up Your Video/02 - AC-DC - That's The Way I Wanna Rock 'n' Roll.mp3;That's The Way I Wanna Rock 'n' Roll;02;1988;Hard Rock;3:45
